# Generated by Django 4.0.4 on 2022-04-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('edition', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('book_id', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=30)),
            ],
        ),
    ]
